apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-smoketest-aws
  annotations:
    # Filled from the shared ConfigMap by Kustomize replacements.
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/ROLE
    eks.amazonaws.com/audience: sts.amazonaws.com
    eks.amazonaws.com/sts-regional-endpoints: "true"
automountServiceAccountToken: false
