apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-smoketest
resources:
  - cluster-autoscaler.yaml
  - ebs-csi.yaml
  - aws-pod-identity-webhook.yaml
  - cert-manager.yaml
  - kube-state-metrics.yaml
